# Notebook 03: Preamble Extraction Proposal

## Background and Objectives
This notebook implements the Task 3 preamble extraction proposal across all 193 unique national constitutions.

Following the diagnostic findings of Notebook 02—which revealed that 36 constitutions in the dataset contain full-body legislative articles rather than genuine preambles, and identified HTML entity corruption across multiple records—this pipeline establishes a transparent, rule-based extraction methodology:
1. **Entity and Whitespace Normalization**: Decodes HTML entities (`html.unescape`), resolves unescaped/broken entity remnants (`x27;`, `quot;`, `nbsp;`, `amp;`, stray `gt;`/`lt;`), and collapses multiple spaces and newlines into a single space.
2. **Rule-Based Extraction & Status Assignment**:
   - `no_preamble_in_source`: Constitutions lacking a preamble in the source text (starting immediately with structural headings like Chapter/Article/Part and exceeding 1,000 words). The proposal sets `extracted_text = ""` (0 words) to avoid feeding body text into preamble models.
   - `long_cut`: Constitutions where a genuine preamble is followed immediately by the constitution body (exceeding 1,000 words without a structural start). We locate the first structural heading after word 30 and isolate the preamble.
   - `short_keep`: Standard preambles (<= 400 words, non-structural start). Kept intact.
   - `medium_review`: Preambles between 401 and 1,000 words without structural start. Kept intact for review.
   - `manual_review`: Borderline cases requiring individual inspection (e.g., structural starts under 1,000 words, or long texts without a heading after word 30).
3. **Audit Reports**: Detailed breakdowns per status, crosstabulations against original cluster assignments, cut boundaries, and extracted texts under 30 words.
4. **Data Deliverable**: Generating `data/processed/preamble_extraction_proposal.csv` with columns: `Country, orig_cluster, orig_words, status, rule, extracted_words, extracted_text`.

In [1]:
import os
import re
import html
import json
import pandas as pd
import numpy as np

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 1000)

data_dir = '../data/processed'
clustered_csv_path = os.path.join(data_dir, 'constitution_preamble_clustered.csv')
cleaned_csv_path = os.path.join(data_dir, 'constitution_dataset_cleaned.csv')
proposal_csv_path = os.path.join(data_dir, 'preamble_extraction_proposal.csv')

print(f"Data directory: {os.path.abspath(data_dir)}")

Data directory: /home/devpanchal/Projects/PreambleMap/data/processed

## 1. Data Ingestion and Dataset Alignment

We load `data/processed/constitution_preamble_clustered.csv` (which contains original cluster assignments) and `data/processed/constitution_dataset_cleaned.csv` (which contains raw Preamble text).
- **Cyprus**: Duplicate row 192 (an identical duplicate of row 44) is dropped, yielding exactly 193 unique countries.
- **Slovakia**: The missing raw text (`NaN`) is populated in-memory from Notebook 01 Cell 31 (`slovak_republic` string).

In [2]:
df_clust = pd.read_csv(clustered_csv_path)
df_clean = pd.read_csv(cleaned_csv_path)

# Drop Cyprus duplicate row 192
df = df_clust.drop(index=192).reset_index(drop=True)
df['Preamble'] = df_clean.drop(index=192).reset_index(drop=True)['Preamble']

# Load Slovakia text from Notebook 01 Cell 31
with open('01_data_preprocessing.ipynb', 'r', encoding='utf-8') as f:
    nb01 = json.load(f)
loc = {}
exec(''.join(nb01['cells'][31]['source']), {'df': pd.DataFrame([{'Country': 'Slovakia', 'Preamble': None}])}, loc)
df.loc[df['Country'] == 'Slovakia', 'Preamble'] = loc['slovak_republic']

print(f"Total rows ingested: {len(df)} countries")
print(f"Cyprus occurrences: {len(df[df['Country'] == 'Cyprus'])}")
print(f"Slovakia Preamble length (chars): {len(df.loc[df['Country'] == 'Slovakia', 'Preamble'].values[0])}")

Total rows ingested: 193 countries
Cyprus occurrences: 1
Slovakia Preamble length (chars): 120730

## 2. Step 1: Entity Cleanup and Normalization

Before assigning status or performing cuts, we apply entity and whitespace normalization across all 193 rows:
1. `html.unescape` decodes standard HTML entities.
2. Unescaped/broken entity remnants are repaired:
   - `x27;` -> `'` (apostrophe)
   - `quot;` -> `"` (quotation mark)
   - `nbsp;` -> ` ` (space)
   - `amp;` -> `&` (ampersand)
   - Stray `gt;` and `lt;` are removed using word boundaries (`\bgt;`, `\blt;`) so words like *guilt;*, *silt;*, and *salt;* are preserved.
3. Whitespace characters and newlines are collapsed to single spaces (`\s+` -> `' '`) and stripped.

In [3]:
def clean_entities(text):
    if pd.isna(text):
        return ''
    t = html.unescape(str(text))
    t = t.replace('x27;', "'").replace('quot;', '"').replace('nbsp;', ' ').replace('amp;', '&')
    t = re.sub(r'\bgt;', ' ', t)
    t = re.sub(r'\blt;', ' ', t)
    return re.sub(r'\s+', ' ', t).strip()

raw_texts = df['Preamble'].tolist()
cleaned_texts = [clean_entities(t) for t in raw_texts]
df['cleaned_raw'] = cleaned_texts
df['orig_words'] = df['cleaned_raw'].apply(lambda x: len(x.split()))
df['orig_cluster'] = df['cluster']

changed_rows = sum(1 for r, c in zip(raw_texts, cleaned_texts) if str(r) != c)
print(f"Total rows modified by Step 1 entity/whitespace cleanup: {changed_rows}")

print("\n=== 5 BEFORE / AFTER ENTITY CLEANUP EXAMPLES (WITH CONTEXT) ===")
sample_countries = ['Afghanistan', 'Andorra', 'Bangladesh', 'Central African Rep.', 'New Zealand']
for sc in sample_countries:
    raw_val = df.loc[df['Country'] == sc, 'Preamble'].values[0]
    cl_val = df.loc[df['Country'] == sc, 'cleaned_raw'].values[0]
    
    if sc == 'Afghanistan':
        pat = 'x27;'
    elif sc == 'Andorra':
        pat = 'quot;'
    elif sc == 'Bangladesh':
        pat = 'x27;'
    elif sc == 'Central African Rep.':
        pat = 'quot;'
    elif sc == 'New Zealand':
        pat = 'nbsp;'
    
    idx = raw_val.find(pat)
    start = max(0, idx - 30)
    end_raw = min(len(raw_val), idx + len(pat) + 30)
    snippet_before = raw_val[start:end_raw]
    
    prefix = raw_val[max(0, idx - 20):idx]
    cl_idx = cl_val.find(prefix)
    snippet_after = cl_val[max(0, cl_idx - 10):cl_idx + len(prefix) + 35]
    
    print(f"\nCountry: {sc} (Target Entity: {pat})")
    print(f"  BEFORE: {repr(snippet_before)}")
    print(f"  AFTER:  {repr(snippet_after)}")

Total rows modified by Step 1 entity/whitespace cleanup: 67

=== 5 BEFORE / AFTER ENTITY CLEANUP EXAMPLES (WITH CONTEXT) ===

Country: Afghanistan (Target Entity: x27;)
  BEFORE: ' of the martyrs of the countryx27;s freedom; Comprehending that '
  AFTER:  " of the martyrs of the country's freedom; Comprehending that a un"

Country: Andorra (Target Entity: quot;)
  BEFORE: 'ions, Desiring that the motto quot;virtus, unita, fortiorquot;, w'
  AFTER:  'ions, Desiring that the motto "virtus, unita, fortior", which has'

Country: Bangladesh (Target Entity: x27;)
  BEFORE: ' independent, sovereign Peoplex27;s Republic of Bangladesh; Pled'
  AFTER:  " independent, sovereign People's Republic of Bangladesh; Pledging"

Country: Central African Rep. (Target Entity: quot;)
  BEFORE: ' respect for the principle of quot;Zo Kwe Zoquot; declared by the'
  AFTER:  ' respect for the principle of "Zo Kwe Zo" declared by the Foundin'

Country: New Zealand (Target Entity: nbsp;)
  BEFORE: 'Legislature Act nbsp;gt;nbsp;Amendment Act . Legisl'
  AFTER:  'Legislature Act Amendment Act . Legislature Amendme'

## 3. Step 2: Status Assignment Heuristic

We evaluate each country using the extended `starts_with_structure` heuristic and word count bands:

1. `starts_with_structure`: Checks the first 12 words of the text for:
   - Structural keywords: `Part`, `Chapter`, `Title`, `Article`, `Section`, `Book`, `Schedule`, `Preliminary`.
   - Roman numerals: `I`, `II`, `III`, `IV`, etc.
   - Extended multi-word structural headings: `Fundamental Principles`, `Basic Law`, `General Provisions`, `Instrument of Government`, `Constitution Act`.

2. **Precedence Hierarchy**:
   1. `no_preamble_in_source`: `starts_with_structure is True` and `words > 1000`. Source text contains only constitution body articles. `extracted_text = ""` and `extracted_words = 0`.
   2. `long_cut`: `not starts_with_structure` and `words > 1000`. Locates the first structural heading (`Chapter`, `Title`, `Part`, `Article`, `Art`, `Section`, with optional numeral/Roman numeral) occurring AFTER word 30. The text is cut immediately before this heading. If none is found or the extract would be under 30 words, status is set to `manual_review`.
   3. `short_keep`: `not starts_with_structure` and `words <= 400`. Kept intact.
   4. `medium_review`: `not starts_with_structure` and `401 <= words <= 1000`. Kept intact for review.
   5. `manual_review`: Everything else (e.g. structural start with words <= 1000, or long texts without cut heading).

The resulting extraction proposal is saved to `data/processed/preamble_extraction_proposal.csv`.

In [4]:
extended_phrases = [
    'fundamental principles', 'basic law', 'general provisions',
    'instrument of government', 'constitution act'
]
single_keywords = {
    'part', 'chapter', 'title', 'article', 'section', 'book', 'schedule', 'preliminary'
}
roman_numerals = {'i', 'ii', 'iii', 'iv', 'v', 'vi', 'vii', 'viii', 'ix', 'x', 'xi', 'xii'}

def check_structure_start(text):
    words = text.split()
    first_12 = words[:12]
    first_12_str = ' '.join(first_12).lower()
    has_phrase = any(phrase in first_12_str for phrase in extended_phrases)
    has_kw = any(re.sub(r'^[^\w]+|[^\w]+$', '', w).lower() in single_keywords for w in first_12)
    has_rm = any(re.sub(r'^[^\w]+|[^\w]+$', '', w).lower() in roman_numerals for w in first_12)
    return has_phrase or has_kw or has_rm

numeral_or_roman = r'(?:[0-9]+|[IVXLCDMivxlcdm]+|One|Two|Three|Four|Five|Six|Seven|Eight|Nine|Ten|First|Second|Third|Fourth|Fifth)'
heading_re = re.compile(
    r'\b(Chapter|Title|Part|Article|Art|Section)(?:\s+' + numeral_or_roman + r'\b|\b(?!\s+(?:of|in|and|the|a|an|to|for|with|by|from|or|meant)\b))',
    re.IGNORECASE
)

status_list = []
rule_list = []
extracted_text_list = []
extracted_words_list = []

for i, r in df.iterrows():
    txt = r['cleaned_raw']
    words = txt.split()
    n_words = len(words)
    is_struct = check_structure_start(txt)
    
    if is_struct and n_words > 1000:
        st = 'no_preamble_in_source'
        rl = 'structural_start_and_words_gt_1000'
        ext_txt = ''
        ext_w = 0
    elif (not is_struct) and n_words > 1000:
        prefix_30 = ' '.join(words[:30])
        rest = ' '.join(words[30:])
        m = heading_re.search(rest)
        if m:
            cut_pos = len(prefix_30) + 1 + m.start()
            ext = txt[:cut_pos].strip()
            ext_words = len(ext.split())
            if ext_words >= 30:
                st = 'long_cut'
                rl = f'cut_before_{m.group(0).replace(" ", "_")}'
                ext_txt = ext
                ext_w = ext_words
            else:
                st = 'manual_review'
                rl = 'extract_under_30_words'
                ext_txt = txt
                ext_w = n_words
        else:
            st = 'manual_review'
            rl = 'no_heading_found_after_word_30'
            ext_txt = txt
            ext_w = n_words
    elif (not is_struct) and n_words <= 400:
        st = 'short_keep'
        rl = 'non_structural_words_le_400'
        ext_txt = txt
        ext_w = n_words
    elif (not is_struct) and (401 <= n_words <= 1000):
        st = 'medium_review'
        rl = 'non_structural_words_401_to_1000'
        ext_txt = txt
        ext_w = n_words
    else:
        st = 'manual_review'
        rl = 'structural_start_words_le_1000'
        ext_txt = txt
        ext_w = n_words
        
    status_list.append(st)
    rule_list.append(rl)
    extracted_text_list.append(ext_txt)
    extracted_words_list.append(ext_w)

df['status'] = status_list
df['rule'] = rule_list
df['extracted_text'] = extracted_text_list
df['extracted_words'] = extracted_words_list

# Save proposal CSV
proposal_cols = ['Country', 'orig_cluster', 'orig_words', 'status', 'rule', 'extracted_words', 'extracted_text']
df[proposal_cols].to_csv(proposal_csv_path, index=False)
print(f"Saved proposal CSV to: {proposal_csv_path}")
print(f"Total rows in proposal: {len(df)}")

Saved proposal CSV to: ../data/processed/preamble_extraction_proposal.csv
Total rows in proposal: 193

## 4. Step 3: Diagnostic Reports

We generate detailed reports inspecting status distributions, cut boundaries, review candidates, and short preambles:
- **3a**: Status value counts and status by original cluster crosstab.
- **3b**: `long_cut` cut boundaries (120 characters before and 120 characters after cut).
- **3c**: `medium_review` countries (first 120 and last 150 characters).
- **3d**: `manual_review` countries (first 150 and last 150 characters).
- **3e**: `no_preamble_in_source` countries (Country, orig_words, orig_cluster).
- **3f**: Preambles with extracted_words < 30.

In [5]:
print("=== REPORT 3A: STATUS VALUE COUNTS ===")
status_counts = df['status'].value_counts()
display(pd.DataFrame({'Count': status_counts, 'Percentage': (status_counts / len(df) * 100).round(2)}))

print("\n=== REPORT 3A: CROSSTAB OF STATUS BY ORIGINAL CLUSTER ===")
crosstab_df = pd.crosstab(df['status'], df['orig_cluster'], margins=True)
display(crosstab_df)

=== REPORT 3A: STATUS VALUE COUNTS ===

                       Count  Percentage
status
short_keep               116       60.10
no_preamble_in_source     30       15.54
medium_review             29       15.03
manual_review             12        6.22
long_cut                   6        3.11

=== REPORT 3A: CROSSTAB OF STATUS BY ORIGINAL CLUSTER ===

orig_cluster            0   1   2   3   4   5   6  All
status
long_cut                0   0   2   1   3   0   0    6
manual_review           0   2   5   1   2   2   0   12
medium_review           1   0   5   6   8   1   8   29
no_preamble_in_source   0   0   7   0  11  12   0   30
short_keep             25  15   6  12  17  13  28  116
All                    26  17  25  20  41  28  36  193

In [6]:
print("=== REPORT 3B: LONG_CUT BOUNDARY INSPECTION ===")
long_cut_df = df[df['status'] == 'long_cut'].sort_values('Country')

for _, r in long_cut_df.iterrows():
    c = r['Country']
    txt = r['cleaned_raw']
    ext = r['extracted_text']
    cut_pos = len(ext)
    after_slice = txt[cut_pos:].lstrip()
    
    before_cut = ext[-120:] if len(ext) >= 120 else ext
    after_cut = after_slice[:120]
    
    print(f"\nCountry: {c}")
    print(f"  Original words:  {r['orig_words']}")
    print(f"  Extracted words: {r['extracted_words']}")
    print(f"  Rule applied:    {r['rule']}")
    print(f"  120 chars BEFORE cut: {repr(before_cut)}")
    print(f"  120 chars AFTER cut:  {repr(after_cut)}")

=== REPORT 3B: LONG_CUT BOUNDARY INSPECTION ===

Country: France
  Original words:  13608
  Extracted words: 102
  Rule applied:    cut_before_ARTICLE
  120 chars BEFORE cut: 'd on the common ideal of liberty, equality and fraternity and conceived for the purpose of their democratic development.'
  120 chars AFTER cut:  'ARTICLE France shall be an indivisible, secular, democratic and social Republic. It shall ensure the equality of all cit'

Country: Libya
  Original words:  2952
  Extracted words: 211
  Rule applied:    cut_before_CHAPTER_ONE
  120 chars BEFORE cut: 'ercise of power in the transitional period until the adoption of a permanent Constitution by general popular referendum.'
  120 chars AFTER cut:  'CHAPTER ONE. GENERAL PROVISIONS Article Libya shall be an independent democratic state in which the people shall be the '

Country: New Zealand
  Original words:  3310
  Extracted words: 211
  Rule applied:    cut_before_Part
  120 chars BEFORE cut: 'Parts, as follows:Division IThe Legislative Council. Sections to .Division IIThe House of Representatives. Sections to .'
  120 chars AFTER cut:  'Part Constitution of House. Sections to . Part Preliminary to the Election. Sections to . Part Regulation of Elections. '

Country: Palestine
  Original words:  8212
  Extracted words: 705
  Rule applied:    cut_before_Title_One
  120 chars BEFORE cut: 'act that the Palestine Liberation Organization is the sole and legitimate representative of the Arab Palestinian people.'
  120 chars AFTER cut:  'Title One Article Palestine is part of the larger Arab world, and the Palestinian people are part of the Arab nation. Ar'

Country: Slovakia
  Original words:  19651
  Extracted words: 118
  Rule applied:    cut_before_CHAPTER_ONE
  120 chars BEFORE cut: 'nomic prosperity, that is, we, the citizens of the Slovak Republic, adopt through our representatives this Constitution:'
  120 chars AFTER cut:  'CHAPTER ONE Part One. Basic Provisions Article 1 The Slovak Republic is a sovereign, democratic state governed by the ru'

Country: Suriname
  Original words:  11853
  Extracted words: 182
  Rule applied:    cut_before_CHAPTER_I
  120 chars BEFORE cut: 'd international solidarity, SOLEMNLY DECLARE, TO ACCEPT, AS A RESULT OF THE PLEBISCITE HELD, THE FOLLOWING CONSTITUTION.'
  120 chars AFTER cut:  'CHAPTER I. SOVEREIGNTY First Section. THE REPUBLIC OF SURINAME Article The Republic of Suriname is a democratic State ba'

In [7]:
print("=== REPORT 3C: MEDIUM_REVIEW (401 TO 1000 WORDS) ===")
med_df = df[df['status'] == 'medium_review'].sort_values('Country')
print(f"Total medium_review countries: {len(med_df)}")

for _, r in med_df.iterrows():
    c = r['Country']
    txt = r['cleaned_raw']
    w = r['orig_words']
    first_120 = txt[:120]
    last_150 = txt[-150:]
    print(f"\nCountry: {c} | Words: {w} | Cluster: {r['orig_cluster']}")
    print(f"  First 120 chars: {repr(first_120)}")
    print(f"  Last 150 chars:  {repr(last_150)}")

=== REPORT 3C: MEDIUM_REVIEW (401 TO 1000 WORDS) ===
Total medium_review countries: 29

Country: Angola | Words: 580 | Cluster: 4
  First 120 chars: 'We, the people of Angola, through its lawful representatives, the legislators of the nation, freely elected in the parli'
  Last 150 chars:  'ure generations and to the exercise of our sovereignty; We hereby pass this Constitution as the Supreme and Fundamental Law of the Republic of Angola.'

Country: Bahrain | Words: 742 | Cluster: 2
  First 120 chars: 'In the name of God, the Merciful, the Compassionate Constitution of the Kingdom of Bahrain Foreword to the Constitution '
  Last 150 chars:  'al Action Charter and that complement all the unamended texts. We have attached an explanation memorandum which will be used to explain its judgement.'

Country: Belize | Words: 486 | Cluster: 4
  First 120 chars: 'WHEREAS the people of Belize-affirm that the Nation of Belize shall be founded upon principles which acknowledge the sup'
  Last 150 chars:  'ovisions for ensuring the achievement of the same in Belize; NOW, THEREFORE, the following provisions shall have effect as the Constitution of Belize:'

Country: Benin | Words: 449 | Cluster: 6
  First 120 chars: "Dahomey, proclaimed a Republic on December , , acceded to international sovereignty August , . Having become the People'"
  Last 150 chars:  ' integration; Solemnly adopt the present Constitution which shall be the Supreme Law of the State and to which we swear loyalty, fidelity and respect.'

Country: Burundi | Words: 419 | Cluster: 6
  First 120 chars: 'We the people of Burundi, Conscious of our responsibilities and duties before history and future generations; Reaffirmin'
  Last 150 chars:  'n among the different ethnic groups in our society; We solemnly adopt the present constitution that is the fundamental law of the Republic of Burundi.'

Country: Cabo Verde | Words: 610 | Cluster: 4
  First 120 chars: 'The Proclamation of National Independence is one of the supreme moments in the History of the Cape Verdian nation, resul'
  Last 150 chars:  'ise of power and of citizenship in a climate of liberty, peace, and justice, the basis of all economic, social and cultural development in Cape Verde.'

Country: Cameroon | Words: 835 | Cluster: 6
  First 120 chars: 'We, the people of Cameroon, Proud of our linguistic and cultural diversity, an enriching feature of our national identit'
  Last 150 chars:  'e to the defence of the Fatherland; the State shall guarantee all citizens of either sex the rights and freedoms set forth in the of the Constitution.'

Country: Central African Rep. | Words: 427 | Cluster: 6
  First 120 chars: 'The Central African People Proud of their national unity, linguistic unity and of their ethnic, cultural and religious d'
  Last 150 chars:  ' concerning the prohibition of all forms of discrimination with regard to women as well as those concerning the protection of the rights of the child.'

Country: Chad | Words: 456 | Cluster: 6
  First 120 chars: 'Chad, proclaimed a Republic on November , acceded to national and International sovereignty on August . Since that date,'
  Last 150 chars:  'ub-regional and regional integration; Solemnly adopt this Constitution as supreme law of the State. This is made an integral part of the Constitution.'

Country: Comoros | Words: 408 | Cluster: 4
  First 120 chars: 'The Comorian people solemnly affirm their willto draw from Islam, the religion of the state, the permanent inspiration o'
  Last 150 chars:  'e; the right to an intact environment and the duty of all to preserve that environment. This shall be considered an integral part of the Constitution.'

Country: Cuba | Words: 457 | Cluster: 0
  First 120 chars: 'WE, CUBAN CITIZENS, heirs and continuators of the creative work and the traditions of combativity, firmness, heroism and'
  Last 150 chars:  ' our republic to be the tribute of Cubans to the full dignity of man; AND ADOPT by means of our free vote in a referendum, the following: CONSTITUTION'

Country: Eritrea | Words: 406 | Cluster: 6
  First 120 chars: 'We, the people of Eritrea, united in a common struggle for our rights and common destiny: With Eternal Gratitude to the '
  Last 150 chars:  'ove and solemnly ratify, through the Constituent Assembly, this Constitution as the fundamental law of our Sovereign and Independent State of Eritrea.'

Country: Guyana | Words: 406 | Cluster: 4
  First 120 chars: 'WE THE PEOPLE OF THE CO-OPERATIVE REPUBLIC OF GUYANA, the proud heirs of the indomitable spirit and unconquerable will o'
  Last 150 chars:  'onsensus, after full, free and open discussion, debate and participation, DO ADOPT the following-- CONSTITUTION OF THE CO-OPERATIVE REPUBLIC OF GUYANA'

Country: Hungary | Words: 685 | Cluster: 5
  First 120 chars: 'WE, THE MEMBERS OF THE HUNGARIAN NATION, at the beginning of the new millennium, with a sense of responsibility for ever'
  Last 150 chars:  ' the form in which we want to live. We, the citizens of Hungary, are ready to found the order of our country upon the common endeavours of the nation.'

Country: Iraq | Words: 566 | Cluster: 2
  First 120 chars: 'In the name of God, the Most merciful, the Most compassionate "We have honored the sons of Adam" We, the people of Mesop'
  Last 150 chars:  "ndings of science and man's civilization. The adherence to this Constitution preserves for Iraq its free union of people, of land, and of sovereignty."

Country: Madagascar | Words: 490 | Cluster: 4
  First 120 chars: 'The sovereign Malagasy People, Affirming its belief in Andriamanitra Andriananahary, Resolute to promote and to develop '
  Last 150 chars:  'my to the decentralized collectivities both at the level of the competences and level of financial means; the preservation of human security. Declare:'

Country: Morocco | Words: 577 | Cluster: 2
  First 120 chars: 'With fidelity to its irreversible choice to construct a democratic State of Law, the Kingdom of Morocco resolutely pursu'
  Last 150 chars:  ' of the country, and to harmonize in consequence the pertinent provisions of national legislation. This is made an integral part of this Constitution.'

Country: Myanmar | Words: 458 | Cluster: 3
  First 120 chars: 'Myanmar is a Nation with magnificent historical traditions. We, the National people, have been living in unity and onene'
  Last 150 chars:  'ion of the Republic of the Union of Myanmar through a nation-wide referendum on the Tenth day of Kasone Waning, M.E. The Twenty-Ninth day of May, A.D.'

Country: North Korea | Words: 553 | Cluster: 3
  First 120 chars: 'The Democratic Peoples Republic of Korea is a socialist fatherland of Juche which embodies the idea of and guidance by t'
  Last 150 chars:  'K Socialist Constitution is a Kim II Sung constitution which legally embodies Comrade Kim II Sungs Juche state construction ideology and achievements.'

Country: Pakistan | Words: 425 | Cluster: 2
  First 120 chars: 'Whereas sovereignty over the entire Universe belongs to Almighty Allah alone, and the authority to be exercised by the p'
  Last 150 chars:  'n society through a new order; Do hereby, through our representatives in the National Assembly, adopt, enact and give to ourselves, this Constitution.'

Country: Rwanda | Words: 409 | Cluster: 6
  First 120 chars: 'We, the People of Rwanda,In the wake of the genocide against the Tutsi that was organised and supervised by unworthy lea'
  Last 150 chars:  'on comprising ideas expressed by Rwandans themselves; Now hereby adopt, by referendum, this Constitution as the supreme Law of the Republic of Rwanda:'

Country: Senegal | Words: 430 | Cluster: 6
  First 120 chars: 'The sovereign People of Senegal, PROFOUNDLY attached to their fundamental cultural values which constitutes the cement o'
  Last 150 chars:  'an indispensible cog rouage to the good functioning of the democratic mechanism; Approve and adopt this Constitution of which the is an integral part.'

Country: São Tomé and Principe | Words: 451 | Cluster: 4
  First 120 chars: 'During five centuries the Sao Tomean People were locked in a hard and heroic struggle against colonial domination for th'
  Last 150 chars:  ', and ratification by Popular Referendum, as provided in no. of Article , all of the Constitution, in effect, I promulgate the following Constitution:'

Country: Thailand | Words: 764 | Cluster: 3
  First 120 chars: 'SOMDET PHRA PARAMINTHARAMAHA BHUMIBOL ADUYADEJ SAYAMINTHARATHIRAT BOROMMANATTHABOPHIT Given on the 22nd Day of July B.E.'
  Last 150 chars:  ' as the Interim Constitution of the Kingdom of Thailand until the new Constitution drafted under the provisions of this Constitution comes into force.'

Country: Timor-Leste | Words: 467 | Cluster: 3
  First 120 chars: 'The independence of East Timor, proclaimed by the Frente Revolucionária of Independent East Timor FRETILIN on November ,'
  Last 150 chars:  'onstituent Assembly, meeting in plenary session on March , , approves and decrees the following Constitution of the Democratic Republic of East Timor.'

Country: Tunisia | Words: 494 | Cluster: 2
  First 120 chars: 'In the Name of God, the Merciful, the Compassionate We, the representatives of the Tunisian people, members of the Natio'
  Last 150 chars:  'of national decision-making, world peace, and human solidarity, We, in the name of the Tunisian people, with the help of God, draft this Constitution.'

Country: Turkey | Words: 464 | Cluster: 3
  First 120 chars: 'This Constitution, which affirms the eternal existence of the Turkish Homeland and Nation and the indivisible integrity '
  Last 150 chars:  'nothers rights and freedoms, with mutual sincere love and feelings of fraternity and the desire for, and belief in, Peace at home, peace in the world.'

Country: Tuvalu | Words: 696 | Cluster: 4
  First 120 chars: 'WHEREAS in adopting the Independence Constitution of Tuvalu the people of Tuvalu provided in the to it as follows: WHERE'
  Last 150 chars:  ' this Constitution, and as the guiding principles to be observed in its interpretation and application at all levels of government and organized life.'

Country: Vietnam | Words: 434 | Cluster: 3
  First 120 chars: 'In the course of their millennia-old history, the Vietnamese people, working diligently, creatively, and fighting courag'
  Last 150 chars:  'n with all nations, strictly abide by the Constitution, and win ever greater successes in their effort to renovate, build and defend their Fatherland.'

In [8]:
print("=== REPORT 3D: MANUAL_REVIEW COUNTRIES ===")
manual_df = df[df['status'] == 'manual_review'].sort_values('Country')
print(f"Total manual_review countries: {len(manual_df)}")

for _, r in manual_df.iterrows():
    c = r['Country']
    txt = r['cleaned_raw']
    w = r['orig_words']
    first_150 = txt[:150]
    last_150 = txt[-150:]
    print(f"\nCountry: {c} | Words: {w} | Cluster: {r['orig_cluster']} | Rule: {r['rule']}")
    print(f"  First 150 chars: {repr(first_150)}")
    print(f"  Last 150 chars:  {repr(last_150)}")

=== REPORT 3D: MANUAL_REVIEW COUNTRIES ===
Total manual_review countries: 12

Country: Algeria | Words: 1307 | Cluster: 2 | Rule: no_heading_found_after_word_30
  First 150 chars: 'The Algerian people are a free people; and they are resolved to remain so. Stretching back over thousands of years, their history is marked by a progr'
  Last 150 chars:  'uture generations, the successors of the pioneers of freedom and the founders of the free society. This shall be part and parcel of this Constitution.'

Country: Armenia | Words: 78 | Cluster: 1 | Rule: structural_start_words_le_1000
  First 150 chars: 'The Armenian People, accepting as a basis the fundamental principles of Armenian statehood and pan-national aspirations enshrined in the Declaration o'
  Last 150 chars:  '-being, and civic solidarity of the generations, and affirming its commitment to universal values, adopts the Constitution of the Republic of Armenia.'

Country: China | Words: 1160 | Cluster: 3 | Rule: no_heading_found_after_word_30
  First 150 chars: 'China is one of the countries with the longest histories in the world. The people of all nationalities in China have jointly created a splendid cultur'
  Last 150 chars:  'st take the Constitution as the basic norm of conduct, and they have the duty to uphold the dignity of the Constitution and ensure its implementation.'

Country: Croatia | Words: 642 | Cluster: 5 | Rule: structural_start_words_le_1000
  First 150 chars: 'I Historical Foundations I Historical FoundationsThe millenary identity of the Croatia nation and the continuity of its statehood, confirmed by the co'
  Last 150 chars:  'c state in which equality, freedoms and human rights are guaranteed and ensured, and their economic and cultural progress and social welfare promoted.'

Country: Egypt | Words: 1281 | Cluster: 2 | Rule: no_heading_found_after_word_30
  First 150 chars: 'In the Name of God, Most Gracious, Most Merciful This is Our Constitution Egypt is the gift of the Nile and the gift of Egyptians to humanity. Blessed'
  Last 150 chars:  're the Egyptian people, sovereigns in a sovereign homeland. This is our will and this is the Constitution of our revolution. This is our Constitution.'

Country: Iran | Words: 3223 | Cluster: 2 | Rule: no_heading_found_after_word_30
  First 150 chars: 'In the Name of Allah, the Compassionate, the Merciful We sent aforetime Our apostles with clear signs, and sent down with them the Book and the Balanc'
  Last 150 chars:  ", with the hope that this century will witness the establishment of a universal government of the mustad'afun and the downfall of all the mustakbirun."

Country: Lebanon | Words: 898 | Cluster: 2 | Rule: structural_start_words_le_1000
  First 150 chars: 'PART I BASIC PROVISIONS PART I BASIC PROVISIONS to the ConstitutionLebanon is a sovereign, free, and independent homeland. An ultimate homeland for al'
  Last 150 chars:  'p of any one cannot be expropriated except for reasons of public utility under the conditions prescribed by the law and upon fair compensation to him.'

Country: Liechtenstein | Words: 41 | Cluster: 5 | Rule: structural_start_words_le_1000
  First 150 chars: 'We, John II, by the Grace of God, Prince Regnant of Liechtenstein, Duke of Troppau, Count of Rietberg, etc. etc. etc. make known that the Constitution'
  Last 150 chars:  'oppau, Count of Rietberg, etc. etc. etc. make known that the Constitution of September has been modified by Us with the assent of Our Diet as follows:'

Country: Papua New Guinea | Words: 2011 | Cluster: 4 | Rule: no_heading_found_after_word_30
  First 150 chars: 'WE, THE PEOPLE OF PAPUA NEW GUINEA-united in one nationpay homage to the memory of our ancestors the source of our strength and origin of our combined'
  Last 150 chars:  'f our country and our people, and that the law may impose a similar obligation on non-citizens carrying on economic activities in or from our country.'

Country: Syria | Words: 548 | Cluster: 2 | Rule: structural_start_words_le_1000
  First 150 chars: 'Arab civilization, which is part of human heritage, has faced through its long history great challenges aimed at breaking its will and subjecting it t'
  Last 150 chars:  ' is dedicated. Preserving the dignity of the society and the citizen is an indicator of the civilization of the country and the prestige of the state.'

Country: Tajikistan | Words: 70 | Cluster: 1 | Rule: structural_start_words_le_1000
  First 150 chars: 'WE, THE PEOPLE OF TAJIKISTAN, As an inseparable part of the world community, Realizing our debt and our responsibility to the past, present and future'
  Last 150 chars:  'specting the equality of rights and friendship of all nations and nationalities, Seeking to build a just society, ADOPT AND PROCLAIM THIS CONSTITUTION'

Country: Tonga | Words: 129 | Cluster: 4 | Rule: structural_start_words_le_1000
  First 150 chars: 'Granted by His Majesty King George Tupou I on the fourth day of November One thousand eight hundred and seventy-five and amended in accordance with th'
  Last 150 chars:  'd the year One thousand nine hundred and eighty-eight and revised in accordance with the Laws Consolidation Act on the thirty-first day of December, .'

In [9]:
print("=== REPORT 3E: NO_PREAMBLE_IN_SOURCE COUNTRIES ===")
no_preamble_df = df[df['status'] == 'no_preamble_in_source'][['Country', 'orig_words', 'orig_cluster']].sort_values('Country')
print(f"Total no_preamble_in_source countries: {len(no_preamble_df)}")
display(no_preamble_df)

=== REPORT 3E: NO_PREAMBLE_IN_SOURCE COUNTRIES ===
Total no_preamble_in_source countries: 30

          Country  orig_words  orig_cluster
8       Australia       16303             4
9         Austria       47164             5
22       Botswana       30727             4
30         Canada       20145             4
44         Cyprus       34466             5
46        Denmark        6023             5
58        Finland       12987             5
80         Israel       17607             2
81          Italy       11305             5
82        Jamaica       36267             4
94        Lesotho       42337             4
98     Luxembourg        5848             5
102      Malaysia       62463             4
103      Maldives       23343             2
105         Malta       33577             5
108     Mauritius       36309             4
109        Mexico       61484             4
112        Monaco        4265             5
121   Netherlands        9008             5
127        Norway        7231             5
128          Oman        7427             2
137         Qatar        6637             2
138       Romania       14101             5
145  Saudi Arabia        6580             2
149  Sierra Leone       43149             4
150     Singapore       46473             4
154       Somalia       20776             2
163        Sweden       58431             5
183       Uruguay       29544             4
192         Yemen       11615             2

In [10]:
print("=== REPORT 3F: EXTRACTED WORDS < 30 ===")
short_extracted_df = df[df['extracted_words'] < 30].sort_values('extracted_words', ascending=False)

non_empty_short = short_extracted_df[short_extracted_df['extracted_words'] > 0]
print(f"1. Short Preambles with Non-Empty Text (0 < words < 30): {len(non_empty_short)} countries")
for _, r in non_empty_short.iterrows():
    print(f"\nCountry: {r['Country']} | Words: {r['extracted_words']} | Status: {r['status']} | Cluster: {r['orig_cluster']}")
    print(f"  Full Text: {repr(r['extracted_text'])}")

empty_short = short_extracted_df[short_extracted_df['extracted_words'] == 0]
print(f"\n2. Constitutions with No Preamble in Source (words = 0, empty text): {len(empty_short)} countries")
print(f"Countries: {', '.join(empty_short['Country'].tolist())}")

=== REPORT 3F: EXTRACTED WORDS < 30 ===
1. Short Preambles with Non-Empty Text (0 < words < 30): 3 countries

Country: Latvia | Words: 15 | Status: short_keep | Cluster: 1
  Full Text: 'The people of Latvia, in freely elected Constitutional Assembly, have adopted the following State Constitution:'

Country: Greece | Words: 11 | Status: short_keep | Cluster: 0
  Full Text: 'In the name of the Holy and Consubstantial and Indivisible Trinity'

Country: Belgium | Words: 11 | Status: short_keep | Cluster: 5
  Full Text: 'In the name of the Belgian people, the National Congress decrees:'

2. Constitutions with No Preamble in Source (words = 0, empty text): 30 countries
Countries: Australia, Botswana, Canada, Cyprus, Denmark, Austria, Finland, Israel, Italy, Jamaica, Lesotho, Luxembourg, Malaysia, Maldives, Malta, Mauritius, Mexico, Monaco, Netherlands, Norway, Oman, Qatar, Romania, Saudi Arabia, Sierra Leone, Singapore, Somalia, Sweden, Uruguay, Yemen